sonar.projectKey=doowell

sonar.projectName=doowell

sonar.sources=apps/backend,apps/frontend

sonar.exclusions=**/node_modules/**,**/*.test.js,**/test/**,**/*.spec.ts,**/dist/**,**/build/**,**/migrations/**

sonar.sourceEncoding=UTF-8