sonar.projectKey=doowell

sonar.projectName=doowell

sonar.sources=apps/backend,apps/frontend

sonar.exclusions=**/node_modules/**,**/*.test.js,**/test/**,**/*.spec.ts,**/dist/**,**/build/**,**/migrations/**, **/layout/**,**/*.config.*,seed.ts

sonar.tests=apps/backend/test,apps/backend/src,apps/frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx

sonar.typescript.lcov.reportPaths=apps/backend/coverage/lcov.info,apps/frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
