export const CATEGORY_COLORS = {
  EXERCISE: '#60A5FA',
  HEALTH: '#34D399',
  STUDY: '#FBBF24',
  MIND: '#A78BFA',
  NEUTRAL: '#94A3B8',
} as const;

export const CATEGORY_COLOR_VALUES = [
  CATEGORY_COLORS.EXERCISE,
  CATEGORY_COLORS.HEALTH,
  CATEGORY_COLORS.STUDY,
  CATEGORY_COLORS.MIND,
  CATEGORY_COLORS.NEUTRAL,
] as const;

export type CategoryColor = (typeof CATEGORY_COLOR_VALUES)[number];
