name: SonarQube Analysis

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      # 코드 내려받기
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 소나큐브 스캔 실행
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 품질 게이트확인
      - name: Check Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
